### ISSUE TITLE
downloading subtitles error in openelec

### ISSUE THREAD

**Issue by pogo1975** [CaTzil/service.subtitles.napisy24pl#16]
HI
There is a problem with addon on nightly builds in linux environment
has something to do with unicode convertion
On windows it works ok (builds from the same day) eg 4.10, could you look at it ?

18:49:27 266.065521 T:1602221120  NOTICE: -->Python Interpreter Initialized<--
18:49:28 266.403107 T:1602221120   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc5 in position 27: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.napisy24pl/service.py", line 357, in <module>
                                                subs = Download(params["id"])
                                              File "/storage/.kodi/addons/service.subtitles.napisy24pl/service.py", line 245, in Download
                                                shutil.rmtree(__temp__)
                                              File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
                                              File "/home/neil/projects/OpenELEC.tv/build.OpenELEC-RPi2.arm-devel/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 69, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 27: ordinal not in range(128)
                                            -->End of Python script error report<--
18:49:28 266.488831 T:1833043008   ERROR: GetDirectory - Error getting plugin://service.subtitles.napisy24pl/?action=download&id=85066

**Comment by CaTzil** [comment]
Can you try the hot-fix branch?
https://github.com/CaTzil/service.subtitles.napisy24pl/tree/hot-fix

**Comment by pogo1975** [comment]
hot-fix works ok

**Comment by CaTzil** [comment]
In both of the OSs? win & openElec

**Comment by pogo1975** [comment]
Yes, checked isengard builds from 10.4 (windows) and 12.4 on Raspberry Pi2 Openelec

**Comment by CaTzil** [comment]
Ok, merged to master and posted to XBMC repo.
Thank you!
