### ISSUE TITLE
JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by kokosowy** [CaTzil/service.subtitles.napisy24pl#30]
Weird thing...

Fresh .kodi installation. Just napisy24.pl add-on installed and language set. And I get this python error when trying to search for subtitles:

```
2022-03-28 13:00:39.265 T:59968   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/service.subtitles.napisy24pl/service.py", line 131, in <module>
                                                       search(item)
                                                     File "/home/kodi/.kodi/addons/service.subtitles.napisy24pl/service.py", line 32, in search
                                                       subtitles_list = helper.get_subtitle_list(item)
                                                     File "/home/kodi/.kodi/addons/service.subtitles.napisy24pl/resources/lib/NapisyUtils.py", line 101, in get_subtitle_list
                                                       search_results = self._search_tvshow(item)
                                                     File "/home/kodi/.kodi/addons/service.subtitles.napisy24pl/resources/lib/NapisyUtils.py", line 183, in _search_tvshow
                                                       search_result = json.loads(search_result, encoding="utf-8")
                                                     File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
                                                       return cls(**kw).decode(s)
                                                   TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'
                                                   -->End of Python script error report<--
                                                   
2022-03-28 13:00:39.295 T:59968    INFO <general>: Python interpreter stopped
2022-03-28 13:00:39.307 T:59954   ERROR <general>: GetDirectory - Error getting plugin://service.subtitles.napisy24pl/?action=search&languages=English%2cPolish&preferredlanguage=Polish
```

Here's version information:

```
2022-03-28 12:57:56.469 T:59724    INFO <general>: -----------------------------------------------------------------------
2022-03-28 12:57:56.469 T:59724    INFO <general>: Starting Kodi (19.4 (19.4.0) Git:20220304-nogitfound). Platform: Linux x86 64-bit
2022-03-28 12:57:56.469 T:59724    INFO <general>: Using Release Kodi x64
2022-03-28 12:57:56.469 T:59724    INFO <general>: Kodi compiled 2022-03-04 by GCC 11.2.0 for Linux x86 64-bit version 5.16.8 (331784)
2022-03-28 12:57:56.469 T:59724    INFO <general>: Running on Manjaro Linux 21.2.5, kernel: Linux x86 64-bit version 5.15.28-1-MANJARO
2022-03-28 12:57:56.469 T:59724    INFO <general>: FFmpeg version/source: 4.3.2-Kodi
2022-03-28 12:57:56.469 T:59724    INFO <general>: Host CPU: Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz, 8 cores available
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://xbmc/ is mapped to: /usr/share/kodi
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://xbmcbin/ is mapped to: /usr/lib/kodi
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://masterprofile/ is mapped to: /home/kodi/.kodi/userdata
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://envhome/ is mapped to: /home/kodi
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://home/ is mapped to: /home/kodi/.kodi
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://temp/ is mapped to: /home/kodi/.kodi/temp
2022-03-28 12:57:56.469 T:59724    INFO <general>: special://logpath/ is mapped to: /home/kodi/.kodi/temp
2022-03-28 12:57:56.469 T:59724    INFO <general>: The executable running is: /usr/lib/kodi/kodi.bin
2022-03-28 12:57:56.469 T:59724    INFO <general>: Local hostname: nana
2022-03-28 12:57:56.469 T:59724    INFO <general>: Log File is located: /home/kodi/.kodi/temp/kodi.log
2022-03-28 12:57:56.469 T:59724    INFO <general>: -----------------------------------------------------------------------
2022-03-28 12:57:56.469 T:59724    INFO <general>: loading settings
2022-03-28 12:57:56.470 T:59724    INFO <general>: special://profile/ is mapped to: special://masterprofile/
2022-03-28 12:57:56.470 T:59724   ERROR <general>: CSettings: unable to load settings from special://masterprofile/guisettings.xml, creating new default settings
2022-03-28 12:57:56.475 T:59724    INFO <general>: No settings file to load (special://xbmc/system/advancedsettings.xml)
2022-03-28 12:57:56.475 T:59724    INFO <general>: No settings file to load (special://masterprofile/advancedsettings.xml)
2022-03-28 12:57:56.475 T:59724    INFO <general>: Default Video Player: VideoPlayer
2022-03-28 12:57:56.475 T:59724    INFO <general>: Default Audio Player: paplayer
2022-03-28 12:57:56.475 T:59724    INFO <general>: Disabled debug logging due to GUI setting. Level 0.
2022-03-28 12:57:56.475 T:59724    INFO <general>: Log level changed to "INFO"
2022-03-28 12:57:56.475 T:59724    INFO <general>: creating subdirectories
2022-03-28 12:57:56.475 T:59724    INFO <general>: userdata folder: special://masterprofile/
2022-03-28 12:57:56.475 T:59724    INFO <general>: recording folder: 
2022-03-28 12:57:56.475 T:59724    INFO <general>: screenshots folder: 
2022-03-28 12:57:56.570 T:59724    INFO <general>: creating version table
2022-03-28 12:57:56.571 T:59724    INFO <general>: create addons table
2022-03-28 12:57:56.571 T:59724    INFO <general>: create repo table
2022-03-28 12:57:56.571 T:59724    INFO <general>: create addonlinkrepo table
2022-03-28 12:57:56.571 T:59724    INFO <general>: create update_rules table
2022-03-28 12:57:56.571 T:59724    INFO <general>: create package table
2022-03-28 12:57:56.571 T:59724    INFO <general>: create installed table
2022-03-28 12:57:56.572 T:59724    INFO <general>: CreateAnalytics creating indices
2022-03-28 12:57:56.671 T:59724   ERROR <general>: GetDirectory - Error getting /usr/lib/kodi/addons
2022-03-28 12:57:56.672 T:59724   ERROR <general>: GetDirectory - Error getting special://xbmcbin/addons
2022-03-28 12:57:56.760 T:59724    INFO <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.aac v1.0.2 installed
2022-03-28 12:57:56.760 T:59724    INFO <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.wma v1.0.2 installed
2022-03-28 12:57:56.760 T:59724    INFO <general>: CAddonMgr::FindAddons: game.controller.default v1.0.20 installed
2022-03-28 12:57:56.760 T:59724    INFO <general>: CAddonMgr::FindAddons: game.controller.snes v1.0.19 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.audioengine v1.1.1 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.filesystem v1.1.6 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.general v1.0.5 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.gui v5.15.0 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.main v1.3.0 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.network v1.0.4 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.tools v1.0.4 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.audiodecoder v3.0.0 installed
2022-03-28 12:57:56.761 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.audioencoder v2.1.0 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.game v2.1.1 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.imagedecoder v2.1.1 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.inputstream v3.0.1 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.peripheral v2.0.0 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.pvr v7.1.0 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.screensaver v2.1.0 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.vfs v3.0.0 installed
2022-03-28 12:57:56.762 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.videocodec v2.0.2 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.visualization v3.0.0 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: kodi.resource v1.0.0 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.album.universal v3.1.4 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.artists.universal v4.3.3 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.common.allmusic.com v3.2.2 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.common.fanart.tv v3.6.3 installed
2022-03-28 12:57:56.763 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.common.imdb.com v3.1.6 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.common.musicbrainz.org v2.2.4 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.common.theaudiodb.com v2.0.3 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.common.themoviedb.org v3.2.13 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.generic.albums v1.0.14 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.generic.artists v1.0.14 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.local v1.0.1 installed
2022-03-28 12:57:56.764 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.themoviedb.org v5.2.6 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.themoviedb.org.python v1.3.1+matrix.1 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.tvshows.themoviedb.org v3.5.12 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: metadata.tvshows.themoviedb.org.python v1.3.14 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: repository.xbmc.org v3.2.5 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: resource.images.weathericons.default v1.1.9 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: resource.language.en_gb v2.0.2 installed
2022-03-28 12:57:56.765 T:59724    INFO <general>: CAddonMgr::FindAddons: resource.uisounds.kodi v1.0.1 installed
2022-03-28 12:57:56.766 T:59724    INFO <general>: CAddonMgr::FindAddons: screensaver.xbmc.builtin.black v1.0.34 installed
2022-03-28 12:57:56.766 T:59724    INFO <general>: CAddonMgr::FindAddons: screensaver.xbmc.builtin.dim v1.0.64 installed
2022-03-28 12:57:56.766 T:59724    INFO <general>: CAddonMgr::FindAddons: script.module.pil v5.1.0 installed
2022-03-28 12:57:56.766 T:59724    INFO <general>: CAddonMgr::FindAddons: script.module.pycryptodome v3.4.3 installed
2022-03-28 12:57:56.766 T:59724    INFO <general>: CAddonMgr::FindAddons: service.xbmc.versioncheck v0.5.19+matrix.1 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: skin.estouchy v3.0.6 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: skin.estuary v3.0.5 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: webinterface.default v19.x-2.4.8 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.addon v19.1.0 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.core v0.1.0 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.gui v5.15.0 installed
2022-03-28 12:57:56.767 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.json v12.4.0 installed
2022-03-28 12:57:56.768 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.metadata v2.1.0 installed
2022-03-28 12:57:56.768 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.python v3.0.0 installed
2022-03-28 12:57:56.768 T:59724    INFO <general>: CAddonMgr::FindAddons: xbmc.webinterface v1.0.0 installed
```

Any idea what's going on?

**Comment by CaTzil** [comment]
Yeah, `encoding` was remove in python 3.9 (the new Kodi version is using 3.10)
![image](https://user-images.githubusercontent.com/3762838/160386957-b33c4c74-529a-44ba-81b6-a86644cf8b15.png)

**Comment by kokosowy** [comment]
@CaTzil thanks for looking at it so quickly. Does it mean code needs to be improved or I need to downgrade?

**Comment by CaTzil** [comment]
I've updated my Kodi on my MacOS to latest, and looks like Kodi is using system python (in my case it uses 3.8).

Can you try to install python 3.8 on your system?

**Comment by kokosowy** [comment]
Sure, I can try to install older Python release aside and ask Kodi to use that instead 3.10 from default location, however be aware that this Python 3.10 was delivered together with modern Linux distribution, it's not something I installed by myself. So I believe you code will need to be adopted sooner or later for newer Python releases.

**Comment by CaTzil** [comment]
Can you try the latest version? `3.0.5`

**Comment by CaTzil** [comment]
Should be solved in `v3.0.6`
